kumuluzee:
  name: image-catalog-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/d7ud5c83c09tb0
      connection-url: jdbc:postgresql://ec2-34-233-186-251.compute-1.amazonaws.com/d7ud5c83c09tb0
      username: jtcmiipmqjgedq
      password: a91603371e4c60c1a0f314bd97c0cf99c7be7725b278a0ab7afa3b270f36a349
      listen_addresses: "*"
      pool:
        max-size: 5


